#!/bin/bash

set -eu

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

# Set app specific variables
dbname=$app
dbuser=$app

# Source app helpers
. /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
dbpass=$(ynh_app_setting_get "$app" mysqlpwd)

# Backup dir
backup_dir=$YNH_APP_BACKUP_DIR

# Copy the app source files
final_path="/var/www/$app"
ynh_backup $final_path "www"

# Backup db
root_pwd=$(sudo cat /etc/yunohost/mysql)
sudo su -c "mysql -u root -p$root_pwd $app > ./db.sql"
~                                                                                                                                                                            
~                                                                 
