#!/bin/bash

set -eu

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
nodename=$1
domain=$2
admin=$3
profile=$4

# Set app specific variables
dbname=$app
dbuser=$app
installphp=/scripts/install_cli.php

# Source app helpers
. /usr/share/yunohost/helpers

# Check if admin exists
ynh_user_exists "$admin" \
  || ynh_die "The chosen admin user does not exist."
ynh_app_setting_set $app admin_user $admin

# Get admin email
admin_mail=$(sudo yunohost user info $admin --json | python -c "import json,sys; print json.load(sys.stdin)['mail']")

# Check if a subdomain is passed
domain_len=$(echo $domain | python -c "print len((raw_input().split('.')))")
if [[ $domain_len -le 2 ]]; then
  ynh_die "This app needs a subdomain to work fine"; fi

# Check domain/path availability
sudo yunohost app checkurl $domain -a $app \
  || ynh_die "The path ${domain} is not available for app installation."

# Generate random password
dbpwd=$(ynh_string_random)

# Initialize database
ynh_mysql_create_db $dbname $dbuser $dbpwd

# Copy files to the right place
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/. $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting $app skipped_uris -v "/"
sudo yunohost app ssowatconf

  # Gnu Social installation
sudo php $final_path$installphp --sitename=$nodename --server=$domain --dbtype=mysql --host=localhost --database=$dbname --username=$dbuser --password=$dbpwd --admin-nick=$admin --admin-pass=$dbpwd --admin-email=$admin_mail --site-profile=$profile --fancy=true --ssl=always --skip-config

sleep 1

# Copy config.php file to app path
sudo cp ../conf/config.php $final_path/config.php

# Set permissions to gnusocial directory
sudo chown -R www-data: $final_path

# Change variables in GNU social configuration
sudo sed -i "s/gs_name/$nodename/g" $final_path/config.php
sudo sed -i "s/gs_domain/$domain/g" $final_path/config.php
sudo sed -i "s/yunouser/$dbuser/g" $final_path/config.php
sudo sed -i "s/yunopass/$dbpwd/g" $final_path/config.php
sudo sed -i "s/yunobase/$dbuser/g" $final_path/config.php
sudo sed -i "s/gs_profile/$profile/g" $final_path/config.php

# Start GNU Social queue daemon
sudo bash $final_path/scripts/startdaemons.sh || echo "Queue daemon not started"
