#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
final_path=/var/www/$app

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Stop GNU social queue daemon
sudo bash $final_path/scripts/stopdaemons.sh


#TODO: Parse following two files.
#      Since LDAP plugins are hacked for LDAP integration,
#      copy hacked files before upgrade may work.
#      Upgrade will overwrite the modified files.
#      
# Save hacked files

sudo cp $final_path/plugins/LdapCommon/LdapCommon.php /tmp/LdapCommon.php
sudo cp $final_path/plugins/LdapAuthorization/LdapAuthorizationPlugin.php /tmp/LdapAuthorizationPlugin.php


# Launch GNU social upgrade script
sudo php $final_path/scripts/upgrade.php

# Restore hacked files
sudo mv -f /tmp/LdapCommon.php $path/plugins/LdapCommon/LdapCommon.php 
sudo mv -f /tmp/LdapAuthorizationPlugin.php $path/plugins/LdapAuthorization/LdapAuthorizationPlugin.php 

# Change permisions 
sudo chmod 640 $path/plugins/LdapCommon/LdapCommon.php 
sudo chmod 640 $path/plugins/LdapAuthorization/LdapAuthorizationPlugin.php 


# Start GNU social queue daemon
sudo bash $final_path/scripts/startdaemons.sh


