#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
final_path=/var/www/$app

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Check domain/path availability
sudo yunohost app checkurl $domain -a $app \
  || ynh_die "The url ${domain}${path} is not available for app update."

# Stop GNU social queue daemon
sudo bash $final_path/scripts/stopdaemons.sh

# Copy source files
sudo cp -fa ../sources/. $final_path/

# Set permissions to gnusocial directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
sudo service nginx reload

# Launch GNU social upgrade script
sudo php $final_path/scripts/upgrade.php

# Start GNU social queue daemon
sudo bash $final_path/scripts/startdaemons.sh#!/bin/bash
