#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh

# Exit on command errors and treat unset variables as an error
set -eu

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
final_path=/var/www/$app

# Stop GNU social queue daemon
sudo bash $final_path/scripts/stopdaemons.sh

# setup sources
ynh_setup_sources $final_path www-data

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

sudo yunohost app setting $app skipped_uris -v "/"
sudo yunohost app ssowatconf

# Restart services
sudo service nginx reload

# Launch GNU social upgrade script
sudo php $final_path/scripts/upgrade.php

# Start GNU Social queue daemon
# No daemons activate, and need a service here (TODO)
sudo bash $final_path/scripts/startdaemons.sh
